apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-vxr6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0031-tenant/tkrw-pr712-0075-0031-app/devfile-sample-vxr6@sha256:9bbca811900ac711fa1be600cc594c541bd77bfdf26b3adaf729119fb7376692
        name: my-nodejs
        resources: {}
status: {}
